// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef REAF_CLOCK_H_
#define REAF_CLOCK_H_

#include <absl/base/nullability.h>
#include <absl/synchronization/mutex.h>
#include <absl/time/clock_interface.h>
#include <absl/time/time.h>

namespace reaf {
class MonotonicClock : public absl::Clock {
 public:
  MonotonicClock();
  ~MonotonicClock() override;

  // Returns the current time.
  absl::Time TimeNow() override;

  // Sleeps for the specified duration.
  void Sleep(absl::Duration d) override;

  // Sleeps until the specified time.
  // Only pass times generated by this clock TimeNow function.
  void SleepUntil(absl::Time wakeup_time) override;

  bool AwaitWithDeadline(absl::Mutex* absl_nonnull mu,
                         const absl::Condition& cond,
                         absl::Time deadline) override;

 private:
  absl::Time steady_clock_epoch_;
};

}  // namespace reaf

#endif  //  REAF_CLOCK_H_
